### ISSUE TITLE
Curl error: (3) URL rejected: No host part in the URL

### ISSUE THREAD

**Issue by trexxeon** [pulsejet/nextcloud-oidc-login#281]
Hello,

I followed the authelia integration instructions on: https://www.authelia.com/integration/openid-connect/nextcloud/#openid-connect-login-app

and I am greeted with 
```
Error

    Curl error: (3) URL rejected: No host part in the URL
```

when I press the login with oidc button.

running nextcloud 29

**Comment by spaceone** [comment]
Same problem for me, see → https://github.com/nextcloud/user_oidc/issues/1086

**Comment by spaceone** [comment]
After installing and configuring the "user_oidc" app and accessing "/nextcloud/apps/oidc_login/oidc" I get only the following error message:

```
 Error
 
     Curl error: (3) URL rejected: No host part in the URL
```

I correctly configures provider_url, client_id, client_secret and others.

From looking into the Code the error comes from:
```
#0 /var/www/html/apps/oidc_login/lib/Provider/OpenIDConnectClient.php(271): Jumbojett\OpenIDConnectClient->fetchURL('...')
#1 /var/www/html/apps/oidc_login/lib/Provider/OpenIDConnectClient.php(247): OCA\OIDCLogin\Provider\OpenIDConnectClient->getWellKnown('...')
#2 /var/www/html/apps/oidc_login/3rdparty/jumbojett/openid-connect-php/src/OpenIDConnectClient.php(658): OCA\OIDCLogin\Provider\OpenIDConnectClient->fetchURL('...')
#3 /var/www/html/apps/oidc_login/3rdparty/jumbojett/openid-connect-php/src/OpenIDConnectClient.php(634): Jumbojett\OpenIDConnectClient->getWellKnownConfigValue('...', NULL)
#4 /var/www/html/apps/oidc_login/3rdparty/jumbojett/openid-connect-php/src/OpenIDConnectClient.php(787): Jumbojett\OpenIDConnectClient->getProviderConfigValue('...')
#5 /var/www/html/apps/oidc_login/3rdparty/jumbojett/openid-connect-php/src/OpenIDConnectClient.php(447): Jumbojett\OpenIDConnectClient->requestAuthorization()
#6 /var/www/html/apps/oidc_login/lib/Controller/LoginController.php(59): Jumbojett\OpenIDConnectClient->authenticate()
#7 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(232): OCA\OIDCLogin\Controller\LoginController->oidc()
#8 /var/www/html/lib/private/AppFramework/Http/Dispatcher.php(138): OC\AppFramework\Http\Dispatcher->executeController(Object(OCA\OIDCLogin\Controller\LoginController), '...')
#9 /var/www/html/lib/private/AppFramework/App.php(184): OC\AppFramework\Http\Dispatcher->dispatch(Object(OCA\OIDCLogin\Controller\LoginController), '...')
#10 /var/www/html/lib/private/Route/Router.php(331): OC\AppFramework\App::main('...', '...', Object(OC\AppFramework\DependencyInjection\DIContainer), Array)
#11 /var/www/html/lib/base.php(1060): OC\Route\Router->match('...')
#12 /var/www/html/index.php(49): OC::handleRequest()
```

The fetched URL is `/.well-known/openid-configuration`.

I don't see that my configured provider_url is somewhere read from the config and set in `LoginService->createOIDCClient()`.

Is there some magic involved which should do it? Otherwise I don't understand how it can work at all.

**Comment by spaceone** [comment]
> Is there some magic involved which should do it? Otherwise I don't understand how it can work at all.

Okay got it: https://github.com/pulsejet/nextcloud-oidc-login/blob/master/lib/Provider/OpenIDConnectClient.php#L50-L55
```php
        parent::__construct(
            $this->config->getSystemValue('oidc_login_provider_url'),
            $this->config->getSystemValue('oidc_login_client_id'),
            $this->config->getSystemValue('oidc_login_client_secret'),
            null, // issuer
        );
```

The config fetching returns empty strings.

**Comment by spaceone** [comment]
I tried storing the config in both global and app specific config, but it doesn't work either:

```
# $OCC config:app:get oidc_login provider_url
https://ucs-sso-ng.school.dev/realms/ucs
# $OCC config:system:get oidc_login provider_url
https://ucs-sso-ng.school.dev/realms/ucs

```

**Comment by I3olle** [comment]
I had the same issue but managed to solve it.
Dropping info here in case this helps others.

My problem was, that I had wrongly assumed, I could configure this via environment variables in my docker compose setup. My reasoning was, that I didn't want to manage the `config.php` in git, because it contains sensitive information and is automatically generated during the first setup.

I solved this by creating a `oidc.config.php` and mounting it to `/var/www/html/config/oidc.config.php`.
The reason this additional file works, is [this](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/config_sample_php_parameters.html#loading):

> The config/config.php file may be supplemented by additional *.config.php files placed in the config/ directory (if appropriately named and formatted).

My currently working setup:

Keycloak: v25.0
Nextcloud: v31.0
OpenID Connect Login App: v3.2.2


**oidc.config.php**
```
<?php
$CONFIG = array (
'oidc_login_client_id' => getenv('OIDC_LOGIN_CLIENT_ID'),
'oidc_login_client_secret' => getenv('OIDC_LOGIN_CLIENT_SECRET'),
'oidc_login_provider_url' => getenv('OIDC_LOGIN_PROVIDER_URL'),
'oidc_login_logout_url' => getenv('OIDC_LOGIN_LOGOUT_URL'),
'oidc_login_auto_redirect' => false,
'oidc_login_attributes' => array(
  'id' => 'preferred_username',
  'mail' => 'email',
),
'oidc_login_disable_registration' => false,

// If you are running Nextcloud behind a reverse proxy, make sure this is set
'overwriteprotocol' => 'https',
);
```

excerpt from my **docker-compose.yml**
```
  app:
    image: nextcloud:31.0-fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html:z
      - ./app/oidc.config.php:/var/www/html/config/oidc.config.php:z
      # NOTE: The `volumes` config of the `cron` and `app` containers must match
    environment:
      - MYSQL_HOST=db
      - REDIS_HOST=redis
      # See https://docs.nextcloud.com/server/31/admin_manual/configuration_server/reverse_proxy_configuration.html#defining-trusted-proxies
      # Because we are using Traefik as a reverse proxy and it is running in a Docker network, we can use the Docker network IP range as a trusted proxy.
      # To verify the IP range of your Docker network, you can run `docker network inspect traefik` and look for the `IPAM` section.
      - TRUSTED_PROXIES=172.18.0.0/16
      - NEXTCLOUD_TRUSTED_DOMAINS=https://nextcloud.${DOMAIN_NAME}
      - OIDC_LOGIN_CLIENT_ID=nextcloud
      - OIDC_LOGIN_CLIENT_SECRET=${OIDC_LOGIN_CLIENT_SECRET}
      - OIDC_LOGIN_PROVIDER_URL=https://keycloak.${DOMAIN_NAME}/realms/${KEYCLOAK_REALM_NAME}
      - OIDC_LOGIN_LOGOUT_URL=https://nextcloud.${DOMAIN_NAME}/apps/oidc_login/oidc
      - OIDC_LOGIN_URL=https://nextcloud.${DOMAIN_NAME}/index.php/apps/oidc_login/oidc
    depends_on:
      - db
      - redis
    networks:
      - default

  cron:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html:z
      - ./app/oidc.config.php:/var/www/html/config/oidc.config.php:z
      # NOTE: The `volumes` config of the `cron` and `app` containers must match
    entrypoint: /cron.sh
    environment:
      - OIDC_LOGIN_CLIENT_ID=nextcloud
      - OIDC_LOGIN_CLIENT_SECRET=${OIDC_LOGIN_CLIENT_SECRET}
      - OIDC_LOGIN_PROVIDER_URL=https://keycloak.${DOMAIN_NAME}/realms/${KEYCLOAK_REALM_NAME}
      - OIDC_LOGIN_LOGOUT_URL=https://nextcloud.${DOMAIN_NAME}/apps/oidc_login/oidc
      - OIDC_LOGIN_URL=https://nextcloud.${DOMAIN_NAME}/index.php/apps/oidc_login/oidc
    depends_on:
      - db
      - redis
```
